# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/centos/src/project_data/free/apps/dnnweaver/design/ip/axi_dwidth_converter_64b_to_512b/axi_dwidth_converter_64b_to_512b.xci
# IP: The module: 'axi_dwidth_converter_64b_to_512b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/centos/src/project_data/free/apps/dnnweaver/design/ip/axi_dwidth_converter_64b_to_512b/axi_dwidth_converter_64b_to_512b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64b_to_512b'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/centos/src/project_data/free/apps/dnnweaver/design/ip/axi_dwidth_converter_64b_to_512b/axi_dwidth_converter_64b_to_512b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64b_to_512b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: /home/centos/src/project_data/free/apps/dnnweaver/design/ip/axi_dwidth_converter_64b_to_512b/axi_dwidth_converter_64b_to_512b.xci
# IP: The module: 'axi_dwidth_converter_64b_to_512b' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/centos/src/project_data/free/apps/dnnweaver/design/ip/axi_dwidth_converter_64b_to_512b/axi_dwidth_converter_64b_to_512b_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64b_to_512b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: /home/centos/src/project_data/free/apps/dnnweaver/design/ip/axi_dwidth_converter_64b_to_512b/axi_dwidth_converter_64b_to_512b_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_dwidth_converter_64b_to_512b'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
